[project]
protostar-version = "0.9.4"
lib-path = "lib/cairo_coantracts/src"
cairo-path = ["lib/cairo-conatracts/src"]

[contracts]
main = ["src/main.cairo"]

[profile.testnet.project]
network="testnet"
private-key-path = "./.env"
account-address="0x05E1A58D0Bcc9D0bF93F0b89Ed4228136E1F3e50bf9031B1ff5463a67778BEd5"
